Repository CondeNast/atjson, pull requests merged in 2020-01, with the labels that each got.

#347 Renderer subdocuments in react-renderer
  packages/@atjson/renderer-react/src/index.ts
  packages/@atjson/renderer-react/test/react-renderer-test.tsx
Labels: 🚨 Breaking Change

#353 React-renderer: Use React context for component map
  packages/@atjson/renderer-react/src/index.ts
  packages/@atjson/renderer-react/test/react-renderer-test.tsx
  website/docs/react-renderer.md
Labels: ⚗️ Experiment, 🚨 Breaking Change

#369 🚀 Use a more performant uuid library
  __mocks__/uuid-random.js
  __mocks__/uuid.js
  package-lock.json
  package.json
  packages/@atjson/document/package.json
  packages/@atjson/document/src/annotation.ts
  packages/@atjson/hir/package.json
Labels: ⏱ Performance
