Repository CondeNast/atjson, pull requests merged in 2020-03, with the labels that each got.

#446 fix: add the CKEditor type definition to the npm module
  package.json
Labels: 🐞 Bug

#448 React-renderer: spread annotation children argument
  packages/@atjson/renderer-react/src/index.ts
Labels: 🐞 Bug

#451 chore: store vendorPrefix on annotation instances
  packages/@atjson/document/src/annotation.ts
  packages/@atjson/document/src/collection.ts
  packages/@atjson/document/src/document.ts
  packages/@atjson/document/src/utils.ts
  packages/@atjson/renderer-commonmark/src/index.ts
  packages/@atjson/renderer-hir/src/index.ts
  packages/@atjson/source-html/src/converter/video-embeds.ts
Labels: ⏱ Performance

#455 fix: documentation site and add tests to ensure that it can deploy
  .github/workflows/ci.yml
  website/docs/document-api.mdx
  website/docs/getting-started.md
  website/docs/getting-started.mdx
  website/docs/react-renderer.mdx
  website/package-lock.json
  website/src/components/HTMLRendererDemo.tsx
  website/src/components/Note.tsx
  website/src/components/QuickBrownFox.tsx
  website/src/components/URLPaste.tsx
  website/src/css/custom.css
Labels: 🐞 Bug, 📖 Documentation

#457 Add provider attribute to video embeds
  packages/@atjson/offset-annotations/src/annotations/video-embed.ts
  packages/@atjson/offset-annotations/src/utils/video-urls.ts
  packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts
  packages/@atjson/source-html/src/converter/video-embeds.ts
  packages/@atjson/source-html/test/converter-test.ts
  packages/@atjson/source-url/src/converter.ts
Labels: 🎉 Feature, 🚨 Breaking Change

#461 feat: add support for IGTV
  packages/@atjson/offset-annotations/src/utils/social-urls.ts
  packages/@atjson/source-html/test/converter-test.ts
  packages/@atjson/source-url/test/url-test.ts
Labels: 🎉 Feature
